# Exercise 1.04: Performing Tensor Reshaping and Transposition in TensorFlow

## Problem statement:

Reshape and transpose tensors using TensorFlow

## Index

1. [Import Tensorflow and modify matrix](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Exercise%201.04.ipynb#Import-tensorflor,-create-a-matrix,-and-verify-its-initial-shape)
2. [Transpose Matrix](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Exercise%201.04.ipynb#Transpose-the-Matrix-from-a-2x4-matrix-into-a-4x2-matrix)
3. [Citation](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Exercise%201.04.ipynb#References)

## Import tensorflor, create a matrix, and verify its initial shape

In [3]:
import tensorflow as tf

matrix1 = tf.Variable([[1,2,3,4], [5,6,7,8]])

matrix1.shape.as_list()

[2, 4]

### Use the reshape function to change the matrix's shape

In [4]:
reshape1 = tf.reshape(matrix1, shape=[4,2])

reshape1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

### Verify the result of reshape

In [5]:
reshape1.shape.as_list()

[4, 2]

### Convert the matrix into a matrix with 1 row and 8 columns

In [6]:
reshape2 = tf.reshape(matrix1, shape=[1,8])

reshape2

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]])>

### Verify the new shape of the matrix

In [7]:
reshape2.shape.as_list()

[1, 8]

### Convert the matrix into a matrix with 8 rows and 1 column

In [10]:
reshape3 = tf.reshape(matrix1, shape=[8,1])

reshape3

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])>

### Verify the new shape

In [12]:
reshape3.shape.as_list()

[8, 1]

### Turn the matrix into a 2x2x2 tensor with reshape

In [13]:
reshape4 = tf.reshape(matrix1, shape=[2,2,2])

reshape4

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

### Verify the new shape

In [14]:
reshape4.shape.as_list()

[2, 2, 2]

### Verify the rank of the new tensor

In [15]:
tf.rank(reshape4).numpy()

3

## Transpose the Matrix from a 2x4 matrix into a 4x2 matrix

In [16]:
transpose1 = tf.transpose(matrix1)

transpose1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])>

### Verify this is not the same matrix that was created with reshape

In [17]:
transpose1 == reshape1

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False],
       [False, False],
       [False,  True]])>

### Transpose the 2x2x2 matrix

In [18]:
transpose2 = tf.transpose(reshape4)

transpose2

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])>

<h2 align=center>References</h2>

Moocarme, M., So, A., & Maddalone, A. (2021). The TensorFlow workshop: A hands-on guide to building deep learning models from scratch using real-world datasets. Packt Publishing. 