# Exercise 4.01: Create an Artificial Neural Network with TensorFlow

Create an ANN with an input layer, hidden layer, and ReLU activation function, and an output layer with one unit. Then create some simulation data, and simulate a prediction.

## Import TensorFlow and load TensorBoard

In [63]:
import tensorflow as tf

## Initialize a Keras model of the sequential class

In [64]:
model = tf.keras.Sequential()

## Add an input layer

Add the input_shape argument with size (8,) to represent input data with eight features

In [65]:
model.add(tf.keras.layers.InputLayer(input_shape=(8,), name='Input_layer'))

## Add two Dense class layers

The first will represent your hidden layer with four units and a ReLU activation function. The second will represent your output layer with one unit.

In [66]:
model.add(tf.keras.layers.Dense(4, activation='relu', name='First_hidden_layer'))

model.add(tf.keras.layers.Dense(1, name='Output_layer'))

## View the weights of the layers

Call the variables attribute of the model

In [67]:
model.variables

[<tf.Variable 'First_hidden_layer/kernel:0' shape=(8, 4) dtype=float32, numpy=
 array([[ 0.47704822, -0.06362504, -0.649652  ,  0.38189727],
        [ 0.6901496 ,  0.11631739,  0.06102037,  0.49609822],
        [ 0.60733205,  0.4735424 ,  0.01956207,  0.7034152 ],
        [ 0.20984054, -0.5927912 , -0.08803517, -0.12678057],
        [-0.12253118, -0.10004634,  0.6546523 ,  0.11695278],
        [ 0.46774822,  0.16586232, -0.2885803 , -0.3602824 ],
        [ 0.66688484, -0.67875326,  0.23448873, -0.09327096],
        [ 0.4974864 ,  0.24870116, -0.07869357, -0.2424767 ]],
       dtype=float32)>,
 <tf.Variable 'First_hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[ 0.5769619 ],
        [-0.45292902],
        [-1.0104438 ],
        [-0.14450288]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

## Create a 32x8 Tensor

It will represent a tensor with 32 records and 8 features

In [68]:
data = tf.random.normal((32, 8))

tf.summary.trace_on(graph=True, profiler=True)

## Call the Predict method

and pass in the sample data. This will propagate the data through the network. In each layer, there will be a matrix multiplication of the data with the weights, and the bias will be added before the data is passed as input data to the next layer. This process continues until the final output layer.

In [69]:
model.predict(data)

array([[ 0.56204545],
       [-0.3434476 ],
       [ 0.        ],
       [-1.2869303 ],
       [-1.1651055 ],
       [-0.69182664],
       [-0.98673165],
       [-0.65330225],
       [-1.314677  ],
       [-0.17074284],
       [ 0.        ],
       [-0.23829155],
       [-1.30581   ],
       [ 1.3944101 ],
       [ 1.9503137 ],
       [ 0.7646124 ],
       [-1.2773318 ],
       [-0.0377143 ],
       [ 0.11771536],
       [-0.26818323],
       [-1.4746934 ],
       [ 0.63295406],
       [ 0.        ],
       [-0.5496577 ],
       [-0.7542842 ],
       [-0.32102132],
       [-1.4375086 ],
       [-0.15175326],
       [ 0.3378273 ],
       [-0.39702272],
       [ 0.48181403],
       [-0.11094033]], dtype=float32)