# Exercise 2.04: Loading Text Data for TensorFlow Models

The purpose of this exercise is to load data for batch processing. TensorFlow Hub will be employed to perform a word embedding on the patient reviews.

This project did not work for me on Windows. There is a solution involving curl, but that would be easier for me to work with on Linux. This link might help you: https://www.tensorflow.org/hub/common_issues

## Import tensorflow

In [1]:
import tensorflow as tf

## Create a TensorFlow dataset object

In [2]:
df = tf.data.experimental.make_csv_dataset('C:\\Users\\JoeWi\\TensorFlowWorkshopProjects\\Datasets\\drugsComTrain_raw.tsv',
                                          batch_size=1,
                                          field_delim='\t')

## Create a function that takes a dataset object as input and shuffles, repeats, and beatches the dataset

In [3]:
def prep_ds(ds, shuffle_buffer_size=1024, batch_size=32):
# shuffle the dataset
    ds = ds.repeat()
# batch the dataset
    ds = ds.batch(batch_size)
    return ds

## Apply the prep_ds function to the dataset object

In [4]:
ds = prep_ds(df, batch_size=5)

for x in ds.take(1):
    print(x)

OrderedDict([('', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[214488],
       [179129],
       [ 80843],
       [149131],
       [178948]])>), ('drugName', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Tioconazole'],
       [b'Olanzapine'],
       [b'Delsym'],
       [b'Mirena'],
       [b'Victoza']], dtype=object)>), ('condition', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Vaginal Yeast Infection'],
       [b'Bipolar Disorde'],
       [b'Cough'],
       [b'Birth Control'],
       [b'Diabetes, Type 2']], dtype=object)>), ('review', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'"I used Vagistat last night and it is now the following morning. It has definitely helped to the degree that it&#039;s not all I think about. I would recommend this to anyone."'],
       [b'"No nothing good, just constant fatigue and weight gain. It makes me sleepy as hell and makes me even more of a zombie."'],
       [b'"DO NOT TRY IT. I know some of you have had go

## Import the pretrained word embedding model from TensorFlow Hub and create a Keras layer

In [14]:
import tensorflow_hub as hub

embedding = 'https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1'

hub_layer = hub.KerasLayer(embedding, input_shape=[],
                          dtype=tf.string, trainable=True)

URLError: <urlopen error unknown url type: https>

## Take one batch from the dataset, flatten the tensor, and apply the pretrained layer

In [ ]:
for x in ds.take(1):
    print(hub_layer(tf.reshape(x['review'],[-1])))