# Exercise 1.02 - Creating Scalers, Vectors, Matrices, and Tensors in TensorFlow

## Problem Statement: 

Given the breakdown on votes were cast for three different candidates:

- Create a scaler to store the votes cast for Candidate 1 of political party X in district A.

- Create a vector to represent the proportion of votes cast for three different political candidates of political party X in district A and check its shape and rank.

- Create a matrix to represent the votes cast for three different candidates of political parties X and Y and check its shape and rank

- Create a tensor to represent the votes cast for three different candidates in two different districts, for three political parties, and check its shape and rank.

## Index:

- [#1 import libraries](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Exercise%201.02.ipynb#Import-libraries)
- [#2 Create an int variable](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Exercise%201.02.ipynb#Create-a-variable-integer)
- [#3 Create an int vector](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Exercise%201.02.ipynb#Create-a-Vector)
- [#4 Create an int matrix](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Exercise%201.02.ipynb#Create-a-Matrix)
- [#5 Create an int tensor](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Exercise%201.02.ipynb#Create-a-Tensor)

## Import libraries

In [2]:
import tensorflow as tf

## Create a variable integer

In [3]:
int_variable = tf.Variable(4113, tf.int16)
int_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4113>

### print the rank of the variable created (rank 0 = scaler, rank 1 = vector, rank 2 = matrix, rank 3+ = tensor)

Rank is indicated by the output of numpy, which in this case is 0.

In [6]:
tf.rank(int_variable)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
tf.rank(int_variable).numpy()

0

### This output will indicate the variable does not have a shape, which is typical for a scaler.

In [8]:
int_variable.shape

TensorShape([])

In [9]:
int_variable.shape.as_list()

[]

## Create a Vector

Pass a list for the vector to represent the proportion of votes cast for three different candidates, and pass in a second argument for the datatype as tf.float32 to ensure that it is a float datatype.

In [12]:
vector_variable = tf.Variable([0.23, 0.42, 0.35])

vector_variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0.23, 0.42, 0.35], dtype=float32)>

### Print the rank of the vector, rank 1 = vector

In [13]:
tf.rank(vector_variable).numpy()

1

### Print the shape of the vector as a Python list

In [14]:
vector_variable.shape.as_list()

[3]

## Create a Matrix

Pass a list of lists of integers for the matrix to represent the votes cast for three different candidates in two different districts. The matrix will have three columns representing the candidates, and two rows representing the districts.

In [45]:
matrix_variable = tf.Variable([[4113, 7511, 6259], \
                                [3870, 6725, 6962]], tf.int32)

matrix_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[4113, 7511, 6259],
       [3870, 6725, 6962]])>

### Print its rank to verify it's a matrix

In [46]:
tf.rank(matrix_variable).numpy()

2

### Print the shape of the matrix


This represents the amount of rows and columns in each row: [rows, columns]

In [47]:
matrix_variable.shape.as_list()

[2, 3]

## Create a Tensor

Pass in a triple nested list of integers for the tensor to represent the votes cast for three different candidates in two different districts, for three political parties.

It's hard to see, but below the structure is as follows: two arrays are in three groups, and all three groups are in another group all its own. Each array has 3 values, each group of arrays have 2 arrays, and there are three groups of two.

In [54]:
tensor_variable = tf.Variable([[[4113, 7511, 6259], 
                               [3870, 6725, 6962]],
                               
                              [[5102, 7038, 6591],
                               [3661, 5901, 6235]],
                               
                              [[951, 1208, 1098],
                               [870, 645, 948]]])

tensor_variable

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[4113, 7511, 6259],
        [3870, 6725, 6962]],

       [[5102, 7038, 6591],
        [3661, 5901, 6235]],

       [[ 951, 1208, 1098],
        [ 870,  645,  948]]])>

### Confirm its a tensor with a rank of three

In [55]:
tf.rank(tensor_variable).numpy()

3

### print the shape of the tensor

In [56]:
tensor_variable.shape.as_list()

[3, 2, 3]