# Performing Tensor Addition in TensorFlow

## Problem Statement:

"My company has three locations, each with two salespersons and each location sells three products. I am required to sum the tensors to represent the total revenue for each product across locations" (Moocarme et al., 2021).

# Index

1. [Import Tensorflow](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Activity%201.01.ipynb#Import-TensorFlow)
2. [Create Some Scalers](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Activity%201.01.ipynb#Create-some-scalers)
3. [Create a vector and scaler](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Activity%201.01.ipynb#Create-a-vector-and-scaler)
4. [Create three matrices (final)](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Activity%201.01.ipynb#Create-three-matrices)
6. [Citation](http://localhost:8888/notebooks/The-TensorFlow-Workshop/TensorFlow%20Activity%201.01.ipynb#References)

## Import TensorFlow

In [2]:
import tensorflow as tf

## Create some scalers

### Create two scalers representing the sales of product A by each sales person at location 1

In [3]:
locx_salesperson1_prodA = tf.Variable(2706, tf.int32)
locx_salesperson2_prodA = tf.Variable(2386, tf.int32)

### Sum the scalers and print the result

The result gives us the total amount of sales of product A at location 1.

In [4]:
locx_prodA_total_sales = locx_salesperson1_prodA + locx_salesperson2_prodA

print("The total sales of product A at location x was: " + str(locx_prodA_total_sales.numpy()))

The total sales of product A at location x was: 5092


## Create a vector and scaler

The role of a scaler is to add 95 sales to all products sold by salesperson1. A scaler, scales the size of an array by increasing or decreasing each value by its amount. This is simply a more efficient way of tracking total sales, if they all increase or decrease by the same amount across the board.

In [5]:
salesperson1_vec = tf.Variable([2706, 2799, 5102])
salesperson1_scaler = tf.Variable(95)

salesperson1_sales = salesperson1_vec + salesperson1_scaler

print(salesperson1_sales.numpy())

print("The total sales of all products for salesperson1 was: " + str(salesperson1_sales[0].numpy() +
                                                                     salesperson1_sales[1].numpy() +
                                                                     salesperson1_sales[2].numpy()))

[2801 2894 5197]
The total sales of all products for salesperson1 was: 10892


## Create three matrices

Each matrix represents the quantity of sales of each product by each sales person at each location.

In [6]:
locx_matrix = tf.Variable([[2706, 2799, 5102], 
                           [2386, 4089, 5932]])

locy_matrix = tf.Variable([[5901, 1208, 645],
                           [6235, 1098, 948]])

locz_matrix = tf.Variable([[3908, 2339, 5520],
                           [4544, 1978, 4729]])

loc_matrix_sum = locx_matrix + locy_matrix + locz_matrix

print(loc_matrix_sum.numpy())

[[12515  6346 11267]
 [13165  7165 11609]]


<h2 align=center>References</h2>

Moocarme, M., So, A., & Maddalone, A. (2021). The TensorFlow workshop: A hands-on guide to building deep learning models from scratch using real-world datasets. Packt Publishing. 